job.type: train
job.device: 'cuda'
dataset.name: fbwq_full
model: relational_tucker3

relational_tucker3:
  entity_embedder:
    dim: 256
    dropout: 0.02
    regularize: 'lp'
    regularize_weight: 4e-12

  relation_embedder:
    dim: 128
    dropout: 0.3
    regularize: 'lp'
    regularize_weight: 6e-16
    base_embedder:
      dim: 128
      dropout: 0.3
      regularize: 'lp'
      regularize_weight: 6e-12

train:
  max_epochs: 50
  optimizer.default:
    type: Adagrad
    args:
      lr: 0.1
      weight_decay: 0.4e-7
  batch_size: 16
